[workspace]
members = ["cli", "client", "server"]
resolver = "2"

[workspace.dependencies]
glow = { version = "0.15" }
web-sys = { version = "0.3.72", features = [
    "Window",
    "Document",
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "EventTarget",
    "KeyboardEvent",
    "console",
] }
wasm-bindgen = "0.2"
bytemuck = { version = "1.9.1", features = ["derive"] }
glam = { version = "0.29", features = ["bytemuck"] }
gltf = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
itertools = "0.13"
webbrowser = "1.0.2"
tokio = { version = "1.4.1", features = ["full"] }
anyhow = "1.0"
deno_core = "0.317.0"
tracing = "0.1.40"
tracing-wasm = "0.2.1"