[package]
name = "blocks"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
glam.workspace = true
tracing.workspace = true
serde.workspace = true
wasm-bindgen.workspace = true
tsify.workspace = true
