[package]
name = "net-types"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
serde.workspace = true
derive_more.workspace = true
serde_json.workspace = true

blocks.workspace = true
entities.workspace = true
