[package]
name = "server"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
webbrowser.workspace = true
tokio.workspace = true
anyhow.workspace = true
deno_core.workspace = true
