[package]
name = "player"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
glam.workspace = true
wasm-bindgen.workspace = true
tsify.workspace = true
serde.workspace = true